/* All Tracks --> Basic Programming --> Input/Output --> Basics of Input/Output --> Problem -->
Consecutive Remainders
Tag(s): Basic Programming, Medium-Hard
Alice and Bob playing with numbers today!
Alice says three numbers p, a, b. p, as you may guess, is prime.
Bob, on his turn, want to find integer 0<=x<=p such that (x+b)^a =~ x^a mod p. But finding just one such number is boring, so Bob wants to find few such numbers.
If there are less than 10 such x, print all of them. Else print 10 different x, satisfying equation above.

Input Format:
Input contains t testcases. Each testcase given in separate line.
t
p1 a1 b1
p2 a2 b2
.
.
pt at bt

Output Format:
For each testcase, output number of integers you have found. Then output found integers.

Constraints:
1<=t<=10000.
2<=p<=1000000009, p is prime.
0<=a<=1000000000.
0<=b<=p-1.

SAMPLE INPUT 
3
11 5 3
13 5 4
7 4 1
SAMPLE OUTPUT 
4
1 7 9 10 
0

1
3 
Explanation
In first testcase , we have p=11,a=5,b=3. We need to find all x-s such that (x+3)^5=x^5 mod 11. This equation has 4 solutions -- 1,7,9,10. 
For example, (1+3)^5 = 4^5 = 1024 = 1 =1^3 mod 11.
In second testcase p=13,a=5,b=4, and we have no solutions.
In third, we have just one solution.

Hint:Apply Fermat's little theorem - https://fermat-little-theorem.quora.com/

//My C Solution:
#include <math.h>
#define T 10000
#define N 100

int main()
{
    long t,a[T],p[T],b[T],i,j,m,n,l,k,x[N];
    scanf("%ld",&t);
    for(i=0;i<t;i++){
        l=0;
        scanf("%ld",&p[i]);
        scanf("%ld",&a[i]);
        scanf("%ld",&b[i]);
        for(j=0;j<p[i];j++){
            m = (long)(pow((double)j,(double)a[i]));
            m = m % p[i];
            n = (long)(pow((double)(j+b[i]),(double)a[i]));
            if(m==(n%p[i]))
                x[l++]=j;
        }
        printf("%ld\n",l);
        for(k=0;k<l;k++){
            if(l<=10 && k!=10)
                printf("%ld\n",x[k]);
        }
    }
    return 0;
}


*/

/*Editorial:
Setter: Artsem Zhuk
Tester: Hasan Jaddouh
Editorialist: Saatwik Singh Nagpal

Prerequisites: Group Theory, Number Theory.

Problem:
Given three numbers p, a, b, where p is prime. Find a few different integers 0<=x<=p such that (x+b)^a =~ x^a mod p.

Solution:
We are given a field of numbers to us with multiplication and addition modulo p defined in it. Now, let us find a generator g of the multiplicative group in this field. A generator is such a number in the group which satisfies the following:
The set of elements formed by g,g^2,g^3..g^p-1  contains all the elements of the group, which here would be 1,2,3..p-1.
We need it because we can represent the above equivalence in terms of the generator as each of the elements can be generated using the generator. 
Let x=g^i(mod p) and b=g^j(mod p), for some i and j. So, our equivalence becomes :
(g^i + g^j)^a = (g^i)a(mod p)
Let inv(y) be the inverse of y in this field. If we multiply both sides by inv(g^(i*a)), we get:
inv(g^(i*a))*(g^i(1+g^(j-i)))^a =inv(g^(i*a)) * (g^(i*a)) (mod p)
==> inv(g^(i*a)) * (g^(i*a))*(1+g^(j-i))^a = 1(mod p)
==> (1+g^(j-i))^a = 1(mod p)

Remember that (1+g^(j-i))(mod p) also belongs to the same field, hence it can also be generated by the generator g. Let (1+g^(j-i)) =g^k(mod p). 
So, we have the following :
g^k*a = 1(mod p)
We claim that k*a is divisible by p-1, for the above to be true. This is because as g is a generator, so only the values g^0,g^p-1,g^2p-2,.. will be unity. 
So, k*a is divisible by p-1.
Now, we can iterate over k such that k*a is divisible by p-1 and k<p, and use the value of g^k*a to calculate x. We stop when k>p or number of distinct values of x=10.
But how do we find x, given  g^k*a(mod p)? Let's see.

We know that:
(1+g^(j-i))^a = g^k (mod p)
==> g^(j-i) = (g^k)-1 (mod p)
Substitute g^i as x and g^j as b.
==> b*inv(x) = (g^k)-1(mod p)
==> x=inv((g^k) -1) * b (mod p)

Tester Solution by Hasan Jaddouh
#include <iostream>
#include <assert.h>
#include <random>
using namespace std;
int T;
long long a,b,p;
long long gcd(long long a,long long b){
	if(b==0)return a;
	return gcd(b,a%b);
}
long long pw(long long b,long long k,long long md){
	long long ret=1;
	long long p2=b;
	while(k){
		if(k%2){
			ret *= p2;
			ret %= md;
		}
		k/=2;
		p2 *= p2;
		p2 %= md;
	}
	return ret;
}
int sol[11],sl=0;
bool is_prime(int x){
    for(int i=2;i*i<=x;i++){
        if(x%i==0){
            return false;
        }
    }
    return true;
}
int main(){
	cin.sync_with_stdio(false);
	cin>>T;
	assert(1<=T && T<=10000);
	while(T--){
		cin>>p>>a>>b;
		assert(2<=p && p<=1000000000);
		assert(0<=b && b<=p-1);
		assert(0<=a && a<=1000000000);
		assert(is_prime(p));
		if(b==0){
			int sol=min(p,10ll);
			cout<<sol<<endl;
			for(int i=0;i<sol;i++){
				cout<<i<<" ";
			}
			cout<<endl;
			continue;
		}
		int g=gcd(p-1,a);
		int num= min(10,g-1);
		sl=0;
		int pwr=(p-1)/g;
		for(int i=0;i<1000;i++){
			if(sl == num)break;
			int z=(rand() *1ll* rand() + rand() )% (p-1);
            z += p-1;
            z %= p-1;
            z++;
			int yy= pw (z,pwr,p);
			if(yy==1)continue;
			
			yy = (b * pw(yy-1,p-2,p))%p;
			bool ok=true;
			for(int i=0;i<sl;i++){
				if(sol[i]==yy)ok=false;
			}
			if(ok){
				sol[sl++]=yy;
			}
		}
		//assert(sl == num);
		cout<<sl<<endl;
		for(int i=0;i<sl;i++){
			cout<<sol[i]<<" ";
		//	assert(pw( (sol[i] + b)%p,a,p) == pw(sol[i],a,p));
		}
		cout<<endl;
	}
}


*/


/* Best Submissions:
C:
#include <stdio.h>
long int power(long int x, long int y,long int p)
{
    long int res = 1;      // Initialize result
 
    x = x % p;  // Update x if it is more than or 
                // equal to p
 
    while (y > 0)
    {
        // If y is odd, multiply x with result
        if (y & 1)
            res = (res*x) % p;
 
        // y must be even now
        y = y>>1; // y = y/2
        x = (x*x) % p;  
    }
    return res;
}
int main()
{
    int t;
    long int p,a,b,i,ctr;
    scanf("%d",&t);
    while(t--)
    {
        long int val[10]={};
        ctr=0;
        scanf("%ld %ld %ld",&p,&a,&b);
        
        for(i=0;i<p;i++)
        {
        if(power(i+b,a,p)==power(i,a,p))
        val[ctr++]=i;
        if(ctr==10)
        break;
        }   
   
    printf("%ld\n",ctr);
    for(i=0;i<ctr;i++)
    printf("%ld ",val[i]);
    printf("\n");
    }
    return 0;
}

C++:
//Priyanshu Kumar : IIIT Allahabad
#include<bits/stdc++.h>
using namespace std;
 
#define ll long long int
#define MAX 100005
#define MOD 1000000007
#define sz size()
#define ln length()
#define pb push_back
#define mp make_pair
#define fi first
#define se second
#define si(n) scanf("%d",&n)
#define sl(n) scanf("%lld",&n)
#define pi(n) printf("%d",n)
#define pin(n) printf("%d\n",n);
#define pl(n) printf("%lld",n)
#define pln(n) printf("%lld\n",n);
typedef vector<ll> VI;
 
struct q{
    ll p;
    ll a;
    ll b;
}que[10005];
 
inline ll powmod(ll a,ll b,ll mod)
{
    ll res = 1;
    a %= mod;
    assert(b>=0);
    for( ; b; b >>= 1)
    {
        if(b&1)
            res = res * a % mod;
            a = a * a % mod;
    }
    return res;
}
map <int,int> cc;
vector<ll> fact[10005];
 
ll generator (ll p) {
    
    ll ind = cc[p];
    ll phi = p-1,  n = phi;
    if(fact[ind].size() == 0)
    {
        for (ll i=2; i*i<=n; ++i)
            if (n % i == 0) {
                fact[ind].push_back (i);
                while (n % i == 0)
                    n /= i;
            }
        if (n > 1)
            fact[ind].push_back (n);
    }
    
    for (ll res=2; res<=p; ++res) {
        bool ok = true;
        for (size_t i=0; i<fact[ind].size() && ok; ++i)
            ok &= powmod (res, phi / fact[ind][i], p) != 1;
        if (ok)  return res;
    }
    return -1;
}
 
ll extended_euclid(ll a, ll b, ll &x, ll &y) {
	ll xx = y = 0;
	ll yy = x = 1;
	while (b) {
		ll q = a / b;
		ll t = b; b = a%b; a = t;
		t = xx; xx = x - q*xx; x = t;
		t = yy; yy = y - q*yy; y = t;
	}
	return a;
}
 
ll mod(ll a, ll b) {
	return ((a%b) + b) % b;
}
 
// finds all solutions to ax = b (mod n)
ll modular_linear_equation_solver(ll a, ll b, ll n) {
	ll x, y;
	VI ret;
	ll g = extended_euclid(a, n, x, y);
	if (!(b%g)) {
		x = mod(x*(b / g), n);
		for (int i = 0; i < g; i++)
		{
			return mod(x + i*(n / g), n);
		}
	}
	return -1;
}
 
int main()
{
	ll t,p,a,b,aa,bb,primitive_root,d,m,temp_ans;
	scanf("%lld",&t);
	vector <ll> temp;
	for(int z=0;z<t;z++)
	{
	    sl(que[z].p);
	    sl(que[z].a);
	    sl(que[z].b);
	    temp.pb(que[z].p);
	}
	sort(temp.begin(),temp.end());
	for(int z=0;z<t;z++)
	{
	    cc[que[z].p] = lower_bound(temp.begin(),temp.end(),que[z].p) - temp.begin() ;
	    //cout<<que[z].p<<" "<<cc[que[z].p]<<endl;
	}
    for(int z=0;z<t;z++)
	{
	    p = que[z].p;
	    a = que[z].a;
	    b = que[z].b;
	    if(a == 0 || b == 0)
	    {
	        int limit = min(10LL,p);
	        printf("%d\n",limit);
	        for(int i=0;i<limit;i++)
	            printf("%d ",i);
	        printf("\n");
	        continue;
	    }
	    
        primitive_root = generator (p);
        d = __gcd(a,p-1);
        m = (p-1)/d;
        ll gen = 0;
        gen = powmod(primitive_root,m,p);
        //cout<<primitive_root<<" "<<d<<" "<<m<<" "<<gen<<endl;
        vector <ll> ans;
        for(int i=1;i<d;i++)
        {
            bb = powmod(gen,i,p);
            aa = bb - 1;
            temp_ans = modular_linear_equation_solver(aa, b, p);
            ans.pb(temp_ans);
            if(ans.size() >= 12)
                break;
        }
        ll limit = min((ll)(ans.size()),10LL);
        printf("%lld\n",limit);
        for(int i=0;i<limit;i++)
            printf("%lld ",ans[i]);
        printf("\n");
	}
	return 0;
}

C++14:
// source code by coolreshab 
 
#include<bits/stdc++.h>
using namespace std;
 
#define MAX 100000
#define inf 1000000000
#define mod 1000000007
#define ll long long
 
vector<int>pfact,cool;
ll fast_exp(ll x,ll y,ll m)
{
    ll res=1;
    while(y)
    {
        if(y&1) res=(res*x)%m;
        y>>=1;
        x=(x*x)%m;
    }
    return res;
}
void primefactors(int x)
{
    pfact.clear();
    int i;
    for(i=2;i*i<=x;++i)
    {
        if(x%i==0) pfact.push_back(i);
        while(x%i==0) x/=i;
    }
    if(x>1) pfact.push_back(x);
}
int primitive_root(int x)
{
    int phi=x-1,i;
    bool ok;
    primefactors(phi);
    for(i=2;i<x;++i)
    {
        ok=true;
        for(auto z:pfact)
        {
            if(fast_exp(i,phi/z,x)==1)
            {
                ok=false;
                break;
            }
        }
        if(ok) return i;
    }
    return -1;
}
int main()
{
    ios::sync_with_stdio(false);
    int p,a,b,t,i,g,phi,curr,ans,k;
    cin>>t;
    while(t-->0)
    {
        cin>>p>>a>>b;
        if(b==0)
        {
            for(i=0;i<p;++i)
            {
                cool.push_back(i);
                if(cool.size()==10) break;
            }
        }
        else if(p==2)
        {
            for(i=0;i<p;++i)
            {
                if(fast_exp(i+b,a,p)==fast_exp(i,a,p)) cool.push_back(i);
            }
        }
        else
        {
            g=primitive_root(p);
            phi=p-1;
            k=phi/__gcd(phi,a);
            g=fast_exp(g,k,p);//g^k
            curr=1,i=k;
            while(i<phi and cool.size()<10)
            {
                curr=(1LL*curr*g)%p;
                ans=(1LL*fast_exp(curr-1,p-2,p)*b)%p;
                cool.push_back(ans);
                i+=k;
            }
        }
        cout<<cool.size()<<endl;
        for(auto z:cool) cout<<z<<" ";
        cout<<endl;
        cool.clear();
    }
    return 0;
}

C#:
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
 
namespace practice_2
{
    class may_reminder
    {
 
        static void Main(string[] args)
        {
            ulong t = Convert.ToUInt64(Console.ReadLine());
 
 
            for (ulong i = 0; i <t; i++)
            {
                ulong[] A = Array.ConvertAll(Console.ReadLine().Split(' '), ulong.Parse);
                string s = "";
                int S = 0;
                for (ulong j = 0; j < A[0]; j++)
                {
                    // Console.WriteLine(Math.Pow(j + A[2], A[1]));
 
                    Double d = (Math.Pow(j + A[2], A[1]) % A[0]);
                    Double D = (Math.Pow(j, A[1]) % A[0]);
 
                    if (d==D)
                    {
 
                        S++;
                        s = s + (j).ToString() + " ";
                    }
 
                }
                if (S > 0 && S< 10)
                {
                    Console.WriteLine(S + "\n" + s);
                  // Console.WriteLine(s);
                }
               
                else if(S>10)
                {
                    
                        Console.WriteLine(s.Substring(0,10));
                
                }
                else 
                {
                    Console.WriteLine("0" ); //+"\n");
                   // Console.WriteLine("\n");
                }
 
 
            }
           
 
        }
    }
}

Java:
import java.util.*;
import java.io.*;
import java.math.BigInteger;
 
//
//
//@author usquare
//
//
 
public class ProblemB {
    
    public static long mod = 1000000007;
    
    public static long generator(long p){
        
        long phi=p-1;
        long n=phi;
        ArrayList<Long> fac=new ArrayList<>();
        for(long i=2;i*i<=n;i++){
            if(n%i==0){
                while(n%i==0) n/=i;
                fac.add(i);
            }
        }
        if(n>1) fac.add(n);
        
        for(long i=2;i<=p;i++){
            boolean ok=true;
            for(long j:fac){
                if(pow(i,phi/j,p)==1){
                    ok=false;
                    break;
                }
            }
            if(ok) return i;
        }
        
        return -1;
    }
    
    public static void solve(){
        
        InputReader in = new InputReader(System.in);
        PrintWriter out = new PrintWriter(System.out);
        
        int t=in.nextInt();
        
        while(t-->0){
            long p=in.nextLong();
            long a=in.nextLong();
            long b=in.nextLong();
            
            ArrayList<Long> list=new ArrayList<>();
            long c=0;
            mod=p;
            if(a==0 || b==0){
                for(;c<10 && c<p ;c++) list.add(c);
            }
            else{
                long gen=generator(p);
                long g=gcd(p-1, a);
                long y=(p-1)/g;
                long q=pow(gen, y,p);
                long genpow=q;
                long x=1;
                for(long i=y;i<p-1 && c<10;i+=y){
                    x=mul(b,pow(genpow-1,mod-2,mod));
                    list.add(x);
                    c++;
                    genpow=mul(genpow,q);
                }
                
            }
            out.println(list.size());
            for(long x:list){
                out.print(x+" ");
            }
            out.println();
        }
        
        out.close();
 
    }
    
    public static void main(String[] args) {
    
        new Thread(null ,new Runnable(){
            public void run(){
                try{
                    solve();
                } catch(Exception e){
                    e.printStackTrace();
                }
            }
        },"1",1<<26).start();
    }
 
    
 
    public static class Merge {
        
        public static void sort(int inputArr[]) {
            int length = inputArr.length;
            doMergeSort(inputArr,0, length - 1);
        }
        
        private static void doMergeSort(int[] arr,int lowerIndex, int higherIndex) {        
            if (lowerIndex < higherIndex) {
                int middle = lowerIndex + (higherIndex - lowerIndex) / 2;
                doMergeSort(arr,lowerIndex, middle);
                doMergeSort(arr,middle + 1, higherIndex);
                mergeParts(arr,lowerIndex, middle, higherIndex);
            }
        }
        
        private static void mergeParts(int[]array,int lowerIndex, int middle, int higherIndex) {
            int[] temp=new int[higherIndex-lowerIndex+1];
            for (int i = lowerIndex; i <= higherIndex; i++) {
                temp[i-lowerIndex] = array[i];
            }
            int i = lowerIndex;
            int j = middle + 1;
            int k = lowerIndex;
            while (i <= middle && j <= higherIndex) {
                if (temp[i-lowerIndex] < temp[j-lowerIndex]) {
                    array[k] = temp[i-lowerIndex];
                    i++;
                } else {
                    array[k] = temp[j-lowerIndex];
                    j++;
                }
                k++;
            }
            while (i <= middle) {
                array[k] = temp[i-lowerIndex];
                k++;
                i++;
            }
            while(j<=higherIndex){
                array[k]=temp[j-lowerIndex];
                k++;
                j++;
            }
        }
 
    }
    
    public static boolean isPal(String s){
        for(int i=0, j=s.length()-1;i<=j;i++,j--){
                if(s.charAt(i)!=s.charAt(j)) return false;
        }
        return true;
    }
    public static String rev(String s){
		StringBuilder sb=new StringBuilder(s);
		sb.reverse();
		return sb.toString();
    }
        
    public static long add(long a,long b){
        long x=(a+b);
        while(x>=mod) x-=mod;
        return x;
    }
 
    public static long sub(long a,long b){
        long x=(a-b);
        while(x<0) x+=mod;
        return x;
    }
    
    public static long mul(long a,long b){
        a%=mod;
        b%=mod;
        long x=(a*b);
        return x%mod;
    }
 
    public static long gcd(long x,long y){
	if(x%y==0)
		return y;
	else
		return gcd(y,x%y);
    }
    
    public static int gcd(int x,int y){
	if(x%y==0)
		return y;
	else 
		return gcd(y,x%y);
    }
    
    public static long gcdExtended(long a,long b,long[] x){
        
        if(a==0){
            x[0]=0;
            x[1]=1;
            return b;
        }
        long[] y=new long[2];
        long gcd=gcdExtended(b%a, a, y);
        
        x[0]=y[1]-(b/a)*y[0];
        x[1]=y[0];
        
        return gcd;
    }
    
    public static int abs(int a,int b){
	return (int)Math.abs(a-b);
    }
 
    public static long abs(long a,long b){
	return (long)Math.abs(a-b);
    }
    
    public static int max(int a,int b){
	if(a>b)
		return a;
	else
		return b;
    }
 
    public static int min(int a,int b){
	if(a>b)
		return b;
	else 
		return a;
    }
    
    
 
    public static long pow(long n,long p,long m){
	 long  result = 1;
	  if(p==0)
	    return 1;
          
	while(p!=0)
	{
	    if(p%2==1)
	        result *= n;
	    if(result>=m)
	    result%=m;
	    p >>=1;
	    n*=n;
	    if(n>=m)
	    n%=m;
	}
	return result;
    }
    
    public static long pow(long n,long p){
	long  result = 1;
	  if(p==0)
	    return 1;
          
	while(p!=0)
	{
	    if(p%2==1)
	        result *= n;	    
	    p >>=1;
	    n*=n;	    
	}
	return result;
    }
    
 
 
    public static void debug(Object... o) {
		System.out.println(Arrays.deepToString(o));
	}
 //input sequence
	static class InputReader {
 
		private final InputStream stream;
		private final byte[] buf = new byte[8192];
		private int curChar, snumChars;
		private SpaceCharFilter filter;
 
		public InputReader(InputStream stream) {
			this.stream = stream;
		}
 
		public int snext() {
			if (snumChars == -1)
				throw new InputMismatchException();
			if (curChar >= snumChars) {
				curChar = 0;
				try {
					snumChars = stream.read(buf);
				} catch (IOException e) {
					throw new InputMismatchException();
				}
				if (snumChars <= 0)
					return -1;
			}
			return buf[curChar++];
		}
 
		public int nextInt() {
			int c = snext();
			while (isSpaceChar(c)) {
				c = snext();
			}
			int sgn = 1;
			if (c == '-') {
				sgn = -1;
				c = snext();
			}
			int res = 0;
			do {
				if (c < '0' || c > '9')
					throw new InputMismatchException();
				res *= 10;
				res += c - '0';
				c = snext();
			} while (!isSpaceChar(c));
			return res * sgn;
		}
 
		public long nextLong() {
			int c = snext();
			while (isSpaceChar(c)) {
				c = snext();
			}
			int sgn = 1;
			if (c == '-') {
				sgn = -1;
				c = snext();
			}
			long res = 0;
			do {
				if (c < '0' || c > '9')
					throw new InputMismatchException();
				res *= 10;
				res += c - '0';
				c = snext();
			} while (!isSpaceChar(c));
			return res * sgn;
		}
        //input seqquence ends
		public int[] nextIntArray(int n) {
			int a[] = new int[n];
			for (int i = 0; i < n; i++) {
				a[i] = nextInt();
			}
			return a;
		}
                long[] nextLongArray(int n) {
                    long a[] = new long[n];
                    for (int i = 0; i < n; i++) {
                            a[i] = nextLong();
                    }
                    return a;
                }
		
 
		public String nextLine() {
			int c = snext();
			while (isSpaceChar(c))
				c = snext();
			StringBuilder res = new StringBuilder();
			do {
				res.appendCodePoint(c);
				c = snext();
			} while (!isEndOfLine(c));
			return res.toString();
		}
 
		public boolean isSpaceChar(int c) {
			if (filter != null)
				return filter.isSpaceChar(c);
			return c == ' ' || c == '\n' || c == '\r' || c == '\t' || c == -1;
		}
 
		private boolean isEndOfLine(int c) {
			return c == '\n' || c == '\r' || c == -1;
		}
 
		public interface SpaceCharFilter {
			public boolean isSpaceChar(int ch);
		}
	}
}    

Java 8:
import java.util.*;
import java.io.*;
import java.math.BigInteger;
 
//
//
//@author usquare
//
//
//
public class ProblemB {
    
    public static long mod = 1000000007;
    
    public static long generator(long p){
        
        long phi=p-1;
        long n=phi;
        ArrayList<Long> fac=new ArrayList<>();
        for(long i=2;i*i<=n;i++){
            if(n%i==0){
                while(n%i==0) n/=i;
                fac.add(i);
            }
        }
        if(n>1) fac.add(n);
        
        for(long i=2;i<=p;i++){
            boolean ok=true;
            for(long j:fac){
                if(pow(i,phi/j,p)==1){
                    ok=false;
                    break;
                }
            }
            if(ok) return i;
        }
        
        return -1;
    }
    
    public static void solve(){
        
        InputReader in = new InputReader(System.in);
        PrintWriter out = new PrintWriter(System.out);
        
        int t=in.nextInt();
        
        while(t-->0){
            long p=in.nextLong();
            long a=in.nextLong();
            long b=in.nextLong();
            
            ArrayList<Long> list=new ArrayList<>();
            long c=0;
            mod=p;
            if(a==0 || b==0){
                for(;c<10 && c<p ;c++) list.add(c);
            }
            else{
                long gen=generator(p);
                long g=gcd(p-1, a);
                long y=(p-1)/g;
                long q=pow(gen, y,p);
                long genpow=q;
                long x=1;
                for(long i=y;i<p-1 && c<10;i+=y){
                    x=mul(b,pow(genpow-1,mod-2,mod));
                    list.add(x);
                    c++;
                    genpow=mul(genpow,q);
                }
                
            }
            out.println(list.size());
            for(long x:list){
                out.print(x+" ");
            }
            out.println();
        }
        
        out.close();
 
    }
    
    public static void main(String[] args) {
    
        new Thread(null ,new Runnable(){
            public void run(){
                try{
                    solve();
                } catch(Exception e){
                    e.printStackTrace();
                }
            }
        },"1",1<<26).start();
    }
        
    public static long add(long a,long b){
        long x=(a+b);
        while(x>=mod) x-=mod;
        return x;
    }
 
    public static long sub(long a,long b){
        long x=(a-b);
        while(x<0) x+=mod;
        return x;
    }
    
    public static long mul(long a,long b){
        a%=mod;
        b%=mod;
        long x=(a*b);
        return x%mod;
    }
 
    public static long gcd(long x,long y){
	if(x%y==0)
		return y;
	else
		return gcd(y,x%y);
    }
    
    public static int gcd(int x,int y){
	if(x%y==0)
		return y;
	else 
		return gcd(y,x%y);
    }
    
   //public static long gcdExtended(long a,long b,long[] x){
   //    
   //    if(a==0){
   //        x[0]=0;
   //        x[1]=1;
   //        return b;
   //    }
   //    long[] y=new long[2];
   //    long gcd=gcdExtended(b%a, a, y);
   //    
   //    x[0]=y[1]-(b/a)*y[0];
   //    x[1]=y[0];
   //    
   //    return gcd;
   //}
    
 
    public static long pow(long n,long p,long m){
	 long  result = 1;
	  if(p==0)
	    return 1;
          
	while(p!=0)
	{
	    if(p%2==1)
	        result *= n;
	    if(result>=m)
	    result%=m;
	    p >>=1;
	    n*=n;
	    if(n>=m)
	    n%=m;
	}
	return result;
    }
    
    public static long pow(long n,long p){
	long  result = 1;
	  if(p==0)
	    return 1;
          
	while(p!=0)
	{
	    if(p%2==1)
	        result *= n;	    
	    p >>=1;
	    n*=n;	    
	}
	return result;
    }
    
 
 
    public static void debug(Object... o) {
		System.out.println(Arrays.deepToString(o));
	}
 //input sequence
	static class InputReader {
 
		private final InputStream stream;
		private final byte[] buf = new byte[8192];
		private int curChar, snumChars;
		private SpaceCharFilter filter;
 
		public InputReader(InputStream stream) {
			this.stream = stream;
		}
 
		public int snext() {
			if (snumChars == -1)
				throw new InputMismatchException();
			if (curChar >= snumChars) {
				curChar = 0;
				try {
					snumChars = stream.read(buf);
				} catch (IOException e) {
					throw new InputMismatchException();
				}
				if (snumChars <= 0)
					return -1;
			}
			return buf[curChar++];
		}
 
		public int nextInt() {
			int c = snext();
			while (isSpaceChar(c)) {
				c = snext();
			}
			int sgn = 1;
			if (c == '-') {
				sgn = -1;
				c = snext();
			}
			int res = 0;
			do {
				if (c < '0' || c > '9')
					throw new InputMismatchException();
				res *= 10;
				res += c - '0';
				c = snext();
			} while (!isSpaceChar(c));
			return res * sgn;
		}
 
		public long nextLong() {
			int c = snext();
			while (isSpaceChar(c)) {
				c = snext();
			}
			int sgn = 1;
			if (c == '-') {
				sgn = -1;
				c = snext();
			}
			long res = 0;
			do {
				if (c < '0' || c > '9')
					throw new InputMismatchException();
				res *= 10;
				res += c - '0';
				c = snext();
			} while (!isSpaceChar(c));
			return res * sgn;
		}
        //input seqquence ends
		
		
 
		public String nextLine() {
			int c = snext();
			while (isSpaceChar(c))
				c = snext();
			StringBuilder res = new StringBuilder();
			do {
				res.appendCodePoint(c);
				c = snext();
			} while (!isEndOfLine(c));
			return res.toString();
		}
 
		public boolean isSpaceChar(int c) {
			if (filter != null)
				return filter.isSpaceChar(c);
			return c == ' ' || c == '\n' || c == '\r' || c == '\t' || c == -1;
		}
 
		private boolean isEndOfLine(int c) {
			return c == '\n' || c == '\r' || c == -1;
		}
 
		public interface SpaceCharFilter {
			public boolean isSpaceChar(int ch);
		}
	}
}    
 
Java (nodescript.js):
 
process.stdin.resume();
process.stdin.setEncoding("utf-8");
var stdin_input = "";
 
process.stdin.on("data", function (input) {
    stdin_input += input;                               // Reading input from STDIN
});
 
process.stdin.on("end", function () {
   main(stdin_input);
});
function main(input) {
    var inputs = input.split("\n");
    var testCases = inputs[0];
    var list = inputs.slice(1);
    for (var i = 0; i < testCases; i++) {
        var numbers = list[i].split(" ");
        var p = parseInt(numbers[0]);
        var a = parseInt(numbers[1]);
        var b = parseInt(numbers[2]);
 
        findResult(p, a, b);
 
    }
}
 
function findResult(p, a, b) {
    var listOfAns = [];
    for (var j = 0; j < p; j++) {
        var left = (Math.pow((j + b), a));
        var right = Math.pow(j, a);
        if ((left - right) % p === 0) {
            listOfAns.push(j);
        }
    }
 
    if (listOfAns.length > 10) {
        // Print only 1st ten
        listOfAns = listOfAns.slice(0, 10);
    }
    if (listOfAns.length !== 0) {
        console.log(listOfAns.length);
        listOfAns = listOfAns.join(" ");
        console.log(listOfAns);
    } else {
        console.log(0);
    }
}
 
Python :
from time import time
from random import randint
from fractions import gcd
 
def solve(p, a, b):
    nsol = 0
    sols = []
    for x in xrange(p):
        if pow(x + b, a, p) == pow(x, a, p):
            nsol += 1
            sols.append(x)
            if nsol == 10:
                break
    return nsol, sols
 
def allsols(p):
    for a in xrange(0, p):
        if a > 0:
            g = gcd(a, p - 1) - 1
        else:
            g = p
        for b in xrange(0, p):
            if a > 0 and b > 0:
                gab = gcd(a, b)
            else:
                gab = 0
            nsol = 0
            sols = []
            for x in xrange(p):
                if pow(x + b, a, p) == pow(x, a, p):
                    nsol += 1
                    sols.append(x)
            if g >= 0:
                start = (b * (p - 1)) / 2# / (g + 1))
                start = start % p
            else:
                start = -1
            if len(sols) > 0: # and start not in sols:
                ss3 = solve3(p, a, b, 0, True)
                if ss3[1] != sols:
                    print "a:%d b:%d g:%d %d" % (a, b, g, nsol), sols, start, ss3
 
from time import time
from random import randint
from fractions import gcd
 
def prim_root_unity(p, a, nsol):
    e = (p - 1) // a
    n = 2
    sent = set()
    while len(sent) < nsol:
        ne = pow(n, e, p)
        if ne != 1 and ne not in sent:
            sent.add(ne)
            yield ne
        n += 1
 
def egcd(a, b):
    x,y, u,v = 0,1, 1,0
    while a != 0:
        q,r = b/a,b%a; m,n = x-u*q,y-v*q
        b,a, x,y, u,v = a,r, u,v, m,n
    return b, x, y
 
def modinv(a, m):
    g, x, y = egcd(a, m)
    if g != 1:
        return None  # modular inverse does not exist
    else:
        return x % m
 
def solve2(p, a, b, dur, limit):
    if a == 0 or b == 0:
        return min(p, 10), range(min(p, 10))
    g = gcd(a, p - 1)
    if g == 1:
        return 0, []
    if p < limit:
        return solve(p, a, b)
    nsol = 0
    sols = []
    t0 = time()
    while time() - t0 < dur:
        x = randint(0, p - 1)
        if pow(x + b, a, p) == pow(x, a, p):
            if x not in sols:
                nsol += 1
                sols.append(x)
                if nsol == 10:
                    break
    return nsol, sols
 
def solve3(p, a, b, limit, complete=False):
    if a == 0 or b == 0:
        if complete:
            return p, range(p)
        return min(p, 10), range(min(p, 10))
    g = gcd(a, p - 1)
    if g == 1:
        return 0, []
    if p < limit:
        return solve(p, a, b)
    if complete:
        nsol = g - 1
    else:
        nsol = min((g - 1), 10)
    sols = [(b * modinv(y - 1, p)) % p for y in prim_root_unity(p, g, nsol)]
    return nsol, sorted(sols)
 
def main():
    t = input()
    dur = 14.5 / t
    limit = 0 #30000000 / t
    for _ in xrange(t):
        p, a, b = map(int, raw_input().split())
        nsol, sols = solve3(p, a, b, limit)
        print nsol
        print " ".join(map(str, sols))
main()

Python 3:
from fractions import gcd
 
def prim_root_unity(p, a, nsol):
    e = (p - 1) // a
    n = 2
    sent = set()
    while len(sent) < nsol:
        ne = pow(n, e, p)
        if ne != 1 and ne not in sent:
            sent.add(ne)
            yield ne
        n += 1
 
 
def egcd(a, b):
    x, y, u, v = 0, 1, 1, 0
    while a != 0:
        q, r = b // a, b % a;
        m, n = x - u * q, y - v * q
        b, a, x, y, u, v = a, r, u, v, m, n
    return b, x, y
 
 
def modinv(a, m):
    g, x, y = egcd(a, m)
    if g != 1:
        return None  # modular inverse does not exist
    else:
        return x % m
 
 
 
def solve3(p, a, b, limit, complete=False):
    if a == 0 or b == 0:
        if complete:
            return p, range(p)
        return min(p, 10), range(min(p, 10))
    g = gcd(a, p - 1)
    if g == 1:
        return 0, []
    if complete:
        nsol = g - 1
    else:
        nsol = min((g - 1), 10)
    sols = [(b * modinv(y - 1, p)) % p for y in prim_root_unity(p, g, nsol)]
    return nsol, sorted(sols)
 
 
def main():
    t = int(input())
    limit = 0  # 30000000 / t
    for _ in range(t):
        p, a, b = map(int, input().split())
        nsol, sols = solve3(p, a, b, limit)
        print (nsol)
        print(" ".join(map(str, sols)))
 
 
main()

Ruby:
def consecutive_numbers(p,a,b)
	count = 0
	arr = Array.new
	p.times do |n|
		if ((n+1+b)**a)%p == ((n+1)**a)%p
			count += 1
			arr.push(n+1)
		end
	end
	puts count
	return arr.join(' ')
end
 
t = gets.chomp.to_i
t.times do
	input = gets.chomp.split(' ').map(&:to_i)
	puts consecutive_numbers(input[0], input[1], input[2])
end


*/


/*I/O:
In #1:
3
11 5 3
13 5 4
7 4 1
Out #1:
4
1
7
9
10
0
1
3

In #2:
10
7 9 4
7 2 1
3 8 1
5 10 4
5 3 1
5 1 4
7 6 1
5 7 0
3 2 1
5 9 0
Out#2:
2
4
6
1
3
1
1
1
3
0
0
5
1
2
3
4
5
5
0
1
2
3
4
1
1
5
0
1
2
3
4

In #3:
100
83 51 6
53 37 41
89 92 26
11 8 6
19 8 4
17 66 2
13 12 12
31 92 13
19 78 13
67 13 23
73 36 26
31 16 19
43 69 22
89 80 65
83 49 60
37 72 24
89 71 9
13 71 1
89 54 82
5 59 0
31 29 24
11 49 4
41 99 38
7 74 5
97 43 50
23 44 18
23 47 3
41 12 11
3 55 1
53 46 41
79 52 77
83 21 15
47 17 39
19 64 15
11 13 0
53 33 39
73 14 13
29 5 15
67 1 26
89 68 47
41 47 38
11 78 1
7 87 3
37 69 24
61 24 51
37 37 24
37 81 10
79 5 16
97 84 19
5 52 4
61 84 33
89 64 16
47 38 32
31 49 0
89 88 12
97 5 48
43 3 31
23 74 12
73 83 7
31 48 13
79 93 15
2 9 1
31 89 5
37 26 32
11 16 7
13 27 10
7 31 1
31 89 0
83 41 79
89 83 4
7 98 5
59 47 21
47 65 14
7 34 3
23 67 18
47 98 0
7 4 2
59 50 51
83 31 69
89 62 37
23 97 12
89 85 57
31 98 15
73 96 63
83 71 0
67 57 19
11 71 4
11 76 1
73 40 34
23 84 19
31 20 2
89 88 13
47 83 4
29 3 18
23 28 12
11 2 2
79 68 78
11 1 5
47 82 9
23 97 0
Out #3:
0

0

3
79 76 73 
1
8 
1
17 
1
16 
10
12 4 11 6 5 7 9 8 3 10 
1
9 
5
10 18 3 7 15 
0

10
68 70 13 26 5 58 49 33 1 23 
1
6 
2
8 13 
7
29 64 14 12 10 49 84 
0

10
24 8 14 9 33 18 20 31 23 1 
0

0

1
48 
5
0 1 2 3 4 
0

0

0

1
1 
0

10
16 18 2 6 7 19 4 15 11 8 
0

3
3 15 27 
0

1
6 
10
6 51 7 11 36 37 69 10 72 14 
0

0

1
2 
10
0 1 2 3 4 5 6 7 8 9 
0

1
30 
0

0

3
23 21 19 
0

1
5 
2
3 1 
2
35 15 
10
41 53 60 21 6 5 4 50 11 18 
0

8
13 16 30 29 35 34 11 14 
0

10
62 92 24 89 53 39 25 86 54 83 
3
4 3 2 
10
5 2 46 10 29 14 60 18 43 26 
7
40 76 50 81 23 86 33 
1
31 
10
0 1 2 3 4 5 6 7 8 9 
10
6 46 21 58 28 23 75 68 42 22 
0

2
23 32 
1
17 
0

5
3 7 9 11 15 
2
33 31 
0

0

1
21 
1
2 
2
5 11 
0

10
0 1 2 3 4 5 6 7 8 9 
10
54 44 50 27 6 71 31 76 80 46 
0

1
1 
0

0

1
2 
0

10
0 1 2 3 4 5 6 7 8 9 
1
6 
1
4 
0

1
26 
0

0

1
8 
10
27 68 7 17 50 67 45 9 29 44 
10
0 1 2 3 4 5 6 7 8 9 
2
21 27 
0

1
5 
7
20 35 62 56 50 4 19 
1
2 
9
12 27 20 18 30 11 9 2 17 
10
51 35 45 48 60 62 59 44 1 9 
0

0

1
17 
1
10 
1
40 
0

1
19 
10
0 1 2 3 4 5 6 7 8 9
In #4:
100
787 417 244
941 792 743
643 3 621
797 102 525
3 956 0
929 712 663
521 631 392
677 285 364
947 725 381
449 929 351
199 788 76
523 624 131
631 853 274
61 536 56
853 205 200
653 549 566
283 405 69
89 431 24
53 846 14
103 134 39
401 103 359
443 400 68
709 704 415
461 410 141
839 620 836
359 486 244
199 411 146
257 635 129
337 597 4
743 139 687
797 61 589
709 776 518
523 69 192
797 40 655
607 734 283
797 955 537
883 307 763
839 930 423
47 142 41
257 274 126
151 923 64
491 697 150
739 51 14
691 592 263
929 155 352
977 913 644
181 62 130
887 443 513
199 64 48
199 539 52
839 76 805
983 845 683
277 736 203
883 428 124
797 552 513
619 598 166
701 952 583
421 659 362
619 445 111
7 390 3
23 886 7
103 332 53
953 918 525
83 5 5
577 742 18
853 9 813
887 89 778
887 957 143
719 895 265
433 22 422
283 685 124
229 669 208
739 412 31
283 107 232
73 82 4
509 990 212
139 654 129
887 348 815
251 871 45
131 919 59
631 87 299
241 314 91
23 715 2
727 443 44
947 342 342
673 497 602
73 479 62
163 640 149
127 584 21
983 714 326
211 232 178
211 135 71
661 363 80
571 488 187
757 256 137
79 433 18
199 291 4
199 253 185
397 692 289
257 894 28
Out #4:
2
492 51 
3
847 99 292 
2
424 241 
1
136 
3
0 1 2 
7
227 704 14 133 252 491 39 
0

0

0

0

1
161 
5
15 310 196 82 377 
0

3
30 33 36 
0

0

2
140 74 
0

1
46 
1
32 
0

1
409 
3
79 147 215 
9
103 97 420 229 160 91 361 223 217 
1
421 
1
237 
2
117 135 
0

2
276 57 
0

0

3
401 450 499 
2
115 216 
3
193 71 746 
1
162 
0

0

1
208 
1
3 
1
194 
0

0

2
468 257 
1
214 
0

0

1
116 
10
354 423 442 396 52 797 209 842 518 785 
1
175 
10
193 180 159 40 62 85 107 187 166 153 
1
17 
0

10
263 123 117 125 65 160 92 232 39 209 
1
821 
3
386 142 695 
1
536 
10
572 502 579 305 494 443 506 541 528 42 
0

0

5
5 3 2 1 6 
1
8 
1
25 
10
810 899 901 912 755 475 102 533 175 725 
0

1
568 
2
492 401 
0

0

0

1
222 
0

2
36 214 
1
354 
0

1
71 
1
403 
5
136 95 5 54 13 
1
36 
0

0

2
400 563 
1
75 
10
2 16 20 17 6 15 4 1 5 19 
0

1
776 
6
612 40 641 103 31 132 
0

1
7 
1
53 
1
820 
1
122 
10
30 147 142 54 167 99 152 199 41 184 
10
416 39 186 474 221 603 455 288 571 419 
1
192 
3
28 310 592 
0

2
55 140 
10
170 74 72 127 167 46 86 141 139 43 
3
225 54 280 
1
243 

In #5:
100
430658927 27486059 341103118
956786561 452146330 140053904
435768001 541868112 5471023
825425749 426552945 152702921
426770291 575212180 291375629
783678479 689674887 429934353
810308897 481329504 59118628
159191033 485518880 75671211
785125931 671525825 522874350
724590077 422821280 209820989
867397073 313315744 772829047
734204069 863972690 579755509
227833717 693344696 184097921
788516653 668124248 677763349
798502051 285805260 756212676
413825651 572090370 209467545
689710831 833387550 534280449
885089041 796809222 408504499
138985009 752657808 109999236
65690371 625790520 53937726
750267431 264452001 698282739
246850661 28256160 90522316
817341121 474272848 359093443
553946563 712024248 153327310
853706981 965385624 227784689
459128143 362869496 54033526
612720083 464729148 408116536
816619201 742198000 541105655
84945701 938321860 9450452
543987277 709039716 318348688
638993723 9832936 196685395
727938901 890802250 396877964
661454177 428806096 319031424
803191621 975056670 802770871
536315569 281380768 251252599
29896007 886282075 24493923
855821761 787591220 310153303
426865249 695777148 348004363
606826897 357749249 113386125
480689777 781648448 325414103
2374289 965386565 1167735
204114301 496358500 71234628
578014487 669819177 392011164
222745573 703837548 60900454
236068291 881113400 27342047
697593541 633015240 550773226
511106737 733328688 511085295
869443951 643300500 554398861
667528483 923834511 508460628
30117491 253770010 17565708
159796129 301802608 78555004
42458659 868490590 5251383
849285713 796326311 379748989
895888769 892682000 224783036
940344611 2304420 146633171
560488933 519134742 31667341
804097859 30365111 217293863
433930267 101644848 37242164
373885931 2684504 293680320
577009021 913265370 303891129
17573 75099715 1041
829631017 630514008 689359632
321684947 128880103 188718052
311435543 483251758 99842336
941268763 971370387 302184383
607986781 478689750 362846379
682389373 389144504 3455001
921716017 660796688 725330343
124436687 467472500 92786224
522003329 902703813 495319655
107561497 231042490 46482062
912351301 637414960 745426036
654841457 716008560 618613479
342186967 577764935 29233929
977457889 221723122 800132668
804892229 963505844 537181587
267943967 732959048 79398276
568869421 294718935 562117140
514432759 423438120 1922522
864787477 867010464 48980044
838495423 770027823 562969639
1015697 730119104 64123
529707223 984877164 276477546
941194777 113790696 370538324
511538021 339145968 212068177
512864351 305959478 160961041
362335801 740576050 149900819
776621141 569269020 731711825
943150651 67567755 902636266
980315299 682157380 109779640
873502501 853501080 229028628
31129801 357848970 1304427
183009241 354940920 147899431
953687351 965325020 126232257
95951671 322888530 45724970
444461861 590433620 294544512
323939359 762387444 160383353
56783329 220999023 41232687
579011977 368868000 568314850
790873691 26146050 716598587
Out #5:
10
28513717 327022593 388602016 70859415 53762040 155614038 383935801 155135909 365078827 136278935 
9
430767081 535359854 41745890 176780030 886759609 639952627 774986767 281372803 385965576 
10
229023774 277930417 364381061 252064235 261215359 70393436 552144 185722050 315707543 256867585 
10
278659949 244932990 340454243 614273102 43814366 319116994 347480309 389096946 83509530 677050370 
9
239832736 328643111 174614839 144711467 67697331 417453486 387550114 233521842 322332217 
10
600477271 282414615 698297146 32473044 429187600 769226515 534471941 595906951 599535853 532695173 
10
604928258 581065335 483427247 585775314 69860697 358460484 553267752 558473531 172739172 669613711 
10
148929124 148697071 119922951 26556178 56775860 67765549 109034668 60657875 43868619 79991398 
10
614533919 689526309 484522218 169821290 763529200 274945816 762725646 739518430 520466164 202259015 
10
42052721 708520239 227619689 93797383 345606293 130007870 555351218 22567990 458104476 563430491 
10
521405123 141785341 796483867 224831538 450274238 654087364 332402467 47284013 629562632 307877735 
10
447729930 261549429 487010209 409827274 98915471 381890606 421138534 73065134 260855781 223032224 
10
23614292 108007410 215821997 140119087 171109810 54191173 107195388 120460163 171608709 103376297 
10
765992539 70490321 354469482 376177726 294949336 670685596 378524603 386784987 131952979 68960771 
10
621643979 773933375 490383581 731180737 525973458 310507401 158877697 437517343 64652348 651436569 
9
258913708 308234406 405160857 260628653 102179053 357555104 213022900 309949351 359270049 
10
230465443 496163270 226311185 608737775 353132201 335439618 56977810 45847960 379434507 169520861 
10
398742000 551596928 730549621 180194265 664582227 582506370 821105382 678409123 55602644 304124881 
10
76465770 81712574 31064106 55918456 17932446 5469188 53837383 121239343 16500051 98916189 
10
19788572 4868524 5339480 10744090 42922156 207317 32010116 14363041 59429296 50599843 
10
136805786 589555061 725209719 187936619 646757257 155494866 614315504 77042404 212697062 665446337 
10
162186825 79832386 217934122 224324274 42912466 65076270 244109927 34362844 158850398 201589503 
10
554201764 382160997 157019814 149480956 349715087 541446763 248127448 229123839 210120230 734142036 
10
126783620 334239408 412747913 225320071 67881362 131747094 114980773 177294867 406350005 213794437 
10
757544997 320564938 447357037 344338876 434911182 477714280 589966783 588017616 618674621 647932917 
10
318348657 233473319 424782217 341197562 184886254 76987599 312745193 216773493 415300955 256496636 
10
220084368 605620310 221354067 447152796 192427431 79842992 19391700 477207801 310060824 266271630 
10
14733891 211930792 641916726 591429387 297058077 308520709 304630735 77859969 293635888 91229844 
10
67831763 47867489 8210418 57604086 34253801 22443110 59782614 8950499 16847565 61796545 
10
476220846 397044813 244332293 98606623 105998597 444531081 145963273 43171669 388278815 342932910 
10
228897670 69284326 311833119 445716609 33729907 452825978 456241084 559874768 575902127 562576707 
10
60330223 361237291 43428206 674483722 446224998 564927492 60600737 514817828 5052761 706988836 
10
462184538 61846358 331976773 368599452 17350758 328524384 19460398 501938465 322962355 13898369 
10
436865976 235731328 52240430 353424416 128869858 242514235 596229698 417216816 405823089 292407978 
10
86016158 426867481 43592223 301624934 111294027 108680583 53659735 142531485 231403235 176382387 
10
10675170 23702008 5210228 6438287 5979544 7429019 21087585 6675833 9300078 29432705 
10
647306926 333356323 575072178 353760079 420483087 556419291 7902054 171504623 526262738 272834229 
10
387234289 349335165 89970130 299471799 233750619 106045859 416835513 354872736 101434052 99831799 
10
258214657 310757123 35628159 408513159 20265933 7963300 485477472 473174839 84927613 457812613 
10
277265431 232747225 334706971 446109694 129532506 3417025 285335752 379620413 150084331 397881042 
10
344369 1333914 158691 1325652 526319 400957 1032711 2067507 1513336 173843 
10
25885254 33639569 111721447 199928164 46956154 45890673 94559891 22444172 34949675 283989 
10
559412717 484317318 555074679 437884708 481653648 364061340 36686964 499360099 108527024 273245302 
10
91753846 158478038 200211688 169195107 82407896 166184291 91831229 207689332 97936258 182922992 
10
22200517 89464073 61111429 138708836 50292432 20304413 235383269 228724674 12641369 6506377 
10
340640997 176437356 114166237 499530842 637851948 46536180 300083356 126463119 647259688 474784190 
10
4704672 218394786 175209186 285378423 486481236 99162806 330237644 111610961 445227829 337331661 
10
49076167 798902521 579218234 343920914 95026062 84725228 513862710 663569955 813125679 725581334 
10
632908646 199746675 288305453 35779728 371526337 484518678 253797751 300543777 655406724 331982756 
10
20207837 5637955 5121528 11718999 25309861 28016282 7525389 22086803 19125777 17545022 
10
156602899 37467151 112438153 52739982 7426525 13228312 3113593 120518627 78127532 68012813 
10
10260870 21864693 12792671 4615267 37910802 25181899 91586 42094808 7382776 3738760 
10
346331766 180891671 428734237 184146860 490952219 827870218 285389864 40802487 288645053 123204958 
10
846531928 381136171 241833255 399683960 407191020 252873984 755365319 783497251 811629183 418231749 
9
743733736 353534181 426836604 830376814 396855720 903679237 366874836 440177259 49977704 
10
367306000 86951707 45201616 203485336 408836438 4511425 208802627 161735245 264410796 367086347 
10
149072511 199763461 85169609 641647267 87058467 665797387 256895243 245608620 341195376 329908753 
10
342378691 204322510 125388606 409355678 145200233 318668992 216229524 330421774 415309185 66266329 
10
340138922 9355837 334994945 317525221 174677849 186932348 328406733 55315425 80027180 325940624 
10
377144578 219282275 79755982 455808522 351224213 254403066 300545680 150267732 262376453 208114035 
10
3017 9811 10374 1197 1346 16640 11510 8536 10403 13445 
10
497490892 240881629 640439355 60023643 273402061 25624897 599432441 278716141 318747985 544254356 
10
162587878 50754178 282407800 249347247 218784304 235867538 205304595 172244042 82212717 292063964 
10
166361171 178803445 218890711 115387232 128738690 299636921 41689201 142645619 159622188 20347488 
10
443343098 490826846 622879647 468410271 843369641 532297048 309332707 832923483 123315889 334425893 
10
66381173 163560060 190992618 268682824 564955678 283632232 366308392 34659103 183048741 472694287 
10
205855843 98615411 526943955 528633297 536911956 323828027 80590556 676150427 379807326 291666797 
10
210208953 811268655 494800319 300520243 799674324 406613843 627489351 98192837 490612340 711487848 
10
63517517 78134182 105058823 21919899 14601479 44016023 80652569 48677240 65944847 63336303 
10
499708745 328001258 150794043 243467704 126896527 421790476 305219299 397892960 220685745 48978258 
10
25322338 95295664 8846392 63181943 30011213 3371942 84320466 57707493 31068222 105458989 
10
658305682 789280498 762790949 721661805 470904689 752510382 730800063 211814642 743542322 726780779 
10
332346969 343137661 374327814 298963343 192836429 436280410 337141082 18113989 353928353 254789025 
10
43349246 335125472 304047777 230392704 112045383 200907655 82560334 8905261 320014533 269603792 
10
936286259 777620235 489926354 66120744 91917717 110926075 971888514 115666174 11119305 94244617 
10
432693097 212566568 370524149 82559815 350032017 664503973 614495084 301899455 319907336 551363776 
10
40372603 260633226 244051536 206609689 199715446 235129192 144166534 264259281 251378894 220789000 
10
86293281 489248265 161926472 459479493 38095885 502772258 97135147 154970712 121633214 352989902 
10
107665682 341393899 432188579 379484349 246350431 129481964 428836245 65473935 319208580 110385797 
10
365945363 862694527 591922873 271238161 321151219 840297455 494656214 544569272 223884560 817900383 
10
459852594 545020407 700879440 214520612 509014211 828344345 518558158 319247776 491799680 9516872 
10
690630 737955 719594 808489 803035 256102 125803 801574 485211 909341 
10
283871074 337838664 257051551 129296127 44551412 311509170 350619551 231637027 80163584 154794240 
10
250583619 107204585 349908943 10878868 766646620 333491085 25096469 193845107 253583226 656103302 
10
94231443 15962655 488763458 247303710 399806030 195304450 485757554 341586115 460535205 375139345 
10
179679709 49910245 828754 221038882 213672431 308297986 87178695 274459065 172365438 160435157 
10
203472083 278920878 306877743 184252408 91554289 351297112 140658140 283549171 58292116 263439005 
10
600165125 181583741 301326100 723750623 521488747 104191753 137851910 332234093 281906959 22454658 
10
83069667 499125845 607319738 764054446 56465027 576128306 852913775 130751261 407536730 927200009 
10
332155232 868631873 217296508 467457491 726902106 413277289 255255354 300323627 735276886 714327657 
10
42615183 760916972 248822298 63835509 740140645 277907933 25008076 661734493 150851110 190144902 
10
13765391 16004304 12585317 24845649 15001144 24647699 20600416 27261476 5982885 25318773 
10
82962307 2308645 50570778 111744776 112525397 30314651 132963050 123237532 138026562 59606372 
10
25529646 801761192 627055515 420367657 291684552 305549140 666430093 201381991 825241110 274246195 
10
16439267 34308842 63272737 33309390 65036060 70973122 76894251 35072713 82141764 6437030 
10
3913770 419124028 10046005 136788117 154679994 140237041 323951133 295465143 204506785 297189605 
10
96543922 183621610 272091878 157430310 157514476 304890814 41243164 201805417 235532247 132740645 
10
51748064 40715682 54519388 36457381 55733642 948821 4682520 40424950 2313781 30112023 
10
77511231 119439304 351310919 58697167 497655404 35719632 482868337 409139416 290568782 12742097 
9
28977952 202670319 90246896 488786109 37137552 376362686 774901899 662478476 45297152 

In #6:
100
210392729 273522620 169818093
128692763 977183174 125641189
924836501 876133244 253260887
446365501 167358900 439949021
693712307 157306672 258816003
32553029 765770508 24300992
814501981 339596200 451728950
249573283 324575118 129114274
108651089 477464780 12903318
494904217 213203604 459645673
537526711 874534080 517732006
45816817 970686240 45448114
777786241 181642620 597885019
86342521 435504780 9253088
772959931 732327495 4244415
453297461 985779760 223335602
966258551 930899475 800168148
254767411 998065830 78984653
348733037 294755333 31543327
42280393 632518215 2666377
308864909 756556083 242630559
915269191 986124420 522882276
648007777 693152208 139176298
647541649 203938124 282639165
724515193 798658569 168260490
895699993 643401552 772441813
335289847 616009051 12666530
860078347 552864874 799127431
716034131 669476136 338185921
691633841 30295090 281243528
819499517 584563276 402852249
569288633 143351780 184914336
300882161 872569170 132884943
824943481 175377720 721454110
627584977 247524930 96402080
226576307 368518953 137718684
951766201 700091475 854474018
396667153 387680592 378623095
152809201 252732540 37208463
998878271 508414910 268019944
18465301 839724480 9136885
690502801 900253512 205437655
770793097 733706532 62522233
19915393 998921364 8103225
715069301 86735150 615888751
66374897 508216848 17816161
350398291 654880710 161991511
833346827 65508378 159788041
253969021 194724513 136051795
615600761 758149324 6537160
949956239 164975074 198039187
637613087 141163968 416139499
604088453 17697636 162169351
754889881 540589992 291653402
383170987 179991288 341841763
2573261 628545660 1580592
823546301 68164625 265627645
356630761 137128176 247490844
76334831 4046870 50141367
749268847 683996688 350769622
705683177 423100139 402695874
984497651 243848420 194673780
540384937 377479256 338779488
74469319 832951086 8433453
144974341 143259860 105732006
778746803 413144498 231456986
70567921 954360512 50558441
861914041 863716560 848323769
797613961 23939223 604851392
112365241 467680193 12844469
887023441 807451140 853500397
652649383 101771142 518053573
7554493 584715164 1085243
20504101 127444575 2041838
76763917 160260687 36765413
940735927 17405193 15764
864958333 805150443 260812343
179697571 300034800 87814416
559084307 980425226 489314040
703540069 342946268 298493420
276342719 662224834 165228591
88054801 489804420 8657269
492627841 119903730 9561977
746673841 915833182 34519324
729249361 974590905 73578150
59204419 719324445 7757621
77293019 956175113 61971643
605245139 622980346 300622855
705687071 390525069 597568384
412966517 842711403 28747090
334860499 646746030 5193743
767292329 770496481 251374429
885873269 106845844 743699197
638615881 870955190 220978683
412936471 380581470 345108933
366248789 369869086 215625983
677961967 857164484 493076978
964897697 981791216 74516762
418897273 793250472 257061732
497995021 326117286 147298134
Out #6:
10
91994114 48909402 40886139 61914271 71305508 147706179 20658021 46577094 93210706 9334719 
10
109796719 55242274 22675749 52457732 69801067 68125151 19169738 18169784 82071147 2363745 
10
569375758 711133314 32149333 128545602 732174167 94057076 18455463 364070244 334951824 71980728 
10
339887758 14908789 200091627 380345888 246821868 81853139 440664093 143271687 54556029 264871648 
10
544966724 608997308 134962531 318749305 236957439 164122613 422093906 628659558 125806316 138261881 
10
25041128 11056571 17863713 5824304 18780560 19458691 1481636 17746502 4872285 25719458 
10
109376994 617501130 793437149 604128811 242040255 608366783 753978595 586518520 51649746 588637506 
10
246819922 39880046 245346779 79926558 23892613 180071695 6570973 71915783 220048481 216793015 
10
90007966 88456792 67363731 13582011 98829901 64546324 1601644 36225600 90979006 32224344 
10
175769930 84597573 310667559 39952039 41833328 17629272 488329433 490210722 219495202 445565188 
10
399929069 501842421 473629572 278975125 277346449 62986440 166945766 419518582 180149763 382969778 
10
4327360 23354096 44871527 35017531 42582243 20657548 23062344 10877493 15460333 30978275 
10
122683996 382051076 95962818 731273883 462964490 197647228 677852889 218899643 127626562 410817428 
10
45587903 20281418 67891016 58559803 33841338 82218732 80306641 14738283 72741899 42934837 
10
445476558 282046619 54104347 483271059 171261697 204351957 389358014 379357502 564363559 597453819 
10
411738335 281805407 436131563 255823546 428670312 2652822 40379297 63548711 216986425 132000317 
10
148303724 538188600 641675552 429424376 678383455 499421894 371052571 224200158 676648833 591919991 
10
242154928 167754237 239163998 98207953 11019451 177684069 113906483 124830817 234309591 62267403 
10
68631989 53164806 263701943 28508256 224535721 234419278 280933814 266412596 50777114 36255896 
10
113736 34242929 27237042 36491416 18645872 5876762 13452972 5579743 4699606 26019569 
10
103205310 198138409 222587639 254676824 29733936 21604491 295424724 200679380 174419879 79674535 
10
598609000 805265396 8704628 606784505 177025891 896942970 58918290 775105768 413841915 494893999 
10
566987559 40441757 143665163 357758054 275445791 389390181 521370842 253930354 443795754 383220252 
10
189059018 16816671 387794747 464975511 72532469 448532775 494422007 499951292 601923253 18131988 
10
513823153 160110509 101375768 134889370 360839082 253458604 248693639 542058366 396242969 500623007 
10
297841773 664760925 789807340 726421936 137338549 478648581 694546270 880360034 851468351 230875226 
10
100719062 293161249 238058171 160442710 293269041 210130536 285314134 189948359 183775953 138847364 
10
192751692 737672761 53171494 337865153 275379726 785957481 565074427 692284513 264599253 676613048 
10
444469822 296668184 675692107 595576989 199396547 228981664 188924105 148866546 178451663 498305352 
9
361999076 463479499 491375189 537064232 551012077 564959922 610648965 638544655 48391237 
10
362462234 410081824 26097877 547625821 408028772 145508059 145013676 47752154 306474112 300489419 
10
46674709 368410266 279110186 62031937 347058567 540727001 50466647 244139700 208878778 518726767 
9
79772976 116052673 252720195 15664848 83998609 152332370 216159184 51944545 88224242 
10
3903134 501561111 370107968 292653549 346254753 387898411 135935265 284866196 531700166 740751245 
10
440732596 144069108 545546112 486563600 67073406 282752990 488767278 237491046 170589887 546367110 
10
149642323 182613982 47484164 172962555 72265988 16591635 142471375 41373459 132819948 165791607 
10
161223167 731427800 110537155 696085032 834436264 166910114 480358307 207435578 807690048 906490001 
10
201197928 320215979 11310132 17234984 106898481 30978405 109825820 346824592 201154919 64442799 
10
23206398 111433723 37128488 146119541 119409750 124593828 110571388 50738545 4106644 109130293 
9
495847845 406675545 310823708 413355082 864868299 317503245 420034619 324182782 235010482 
10
14715827 15305177 15524518 6435891 814007 2023780 1818129 15104498 5242192 2035866 
10
473741063 473607496 84588021 396258793 559526430 626458325 21778663 63607046 7239318 166155056 
10
606861522 505750043 19294623 661604668 303632300 354135432 404638564 46666196 688976241 202520821 
10
12726491 12058812 6676220 6881760 2741437 18605857 18613275 4171280 11714373 17011747 
10
405334677 609180837 253694651 361306108 462862929 603874951 571577190 404225278 456274822 83100146 
10
19607064 20735813 40450652 51008666 21705160 33652114 26694174 24279368 21864562 14906622 
10
81945646 29566653 28901840 219962071 114653124 104816222 75809610 92100026 237825695 189217636 
10
143701552 761182557 375146699 546467358 579749546 202127678 619202362 797754901 457863169 644450129 
10
84714850 219993286 247461180 249133439 51971172 72697297 156017468 124737674 151036032 156551096 
10
131994907 37396649 272921377 399063673 48265578 484882952 170089844 181567558 18713811 569407669 
10
509435940 741581674 68100347 606876829 347569524 593151049 191450801 583671540 279745068 728145883 
10
536635715 79560057 475691516 63239307 231919843 530641227 375334508 273495737 174555031 598989189 
10
331336125 484585195 289703177 307981913 183010323 394820265 35118313 202881846 121025591 187599981 
10
666300005 26992321 462734257 173152987 174837809 535982847 350228636 212129822 608894923 143922826 
10
244071127 376230461 209825785 331057908 53951729 164147502 95497678 53162997 71380846 242022622 
10
67556 1494485 13535 408922 1380849 636232 2307001 1669310 644516 1782965 
10
658507632 757906699 117299305 177048966 165529060 484585518 755098635 182113345 549921580 24003715 
10
263659418 124579410 252216614 80762277 190767409 289507190 92094919 295287732 299423527 40154052 
9
1126510 31301877 51728070 41051051 13096732 61477244 50800225 71226418 25066954 
10
138421229 589073279 377808039 319307983 501721722 258769088 348956538 108042743 573884036 290456482 
10
136006421 380702155 264400466 567008424 538756088 469914392 441662056 38586837 627968325 166980882 
9
871270941 488616801 895215903 683861210 887160761 105962661 879105619 301207070 903050581 
10
175493472 533672962 35513156 126100200 406849183 25757898 392090798 6309170 168819084 177275945 
10
56628393 10004402 64317906 21127721 12134084 52058634 43935937 46709420 24883822 40553961 
10
10611954 118765095 137641615 131853245 15483469 92545018 136768255 39275281 102272781 92108338 
10
235772275 619391898 721212559 326744654 351835542 440614055 543788275 7219819 470123532 697919631 
10
67968819 30743319 21259105 18007629 11793503 14737541 26491661 10004740 64085740 5271939 
10
391923754 596965146 661675617 715427501 686565646 700382398 385105962 146948896 365012468 764364542 
10
121537258 402581601 730411206 2103014 541385749 334326304 377560202 318677801 120125397 138757125 
10
77154349 46545493 35339719 107663001 8446062 90943759 50938572 15551480 3105534 96415238 
10
640342797 733150040 395309617 229239891 365507887 452957546 692160897 297178278 429452282 84475647 
10
157671640 590955249 428128810 565688995 492818062 27546566 155224105 170045768 4277257 278317604 
10
1840849 6920535 1452598 3824061 1592544 4756589 333667 3247406 3357839 717443 
10
20442153 18868461 6713890 9051362 12068979 2233140 14321490 2144159 16430575 17900674 
10
66926173 36545922 34176798 69686634 52965760 39820457 18622582 5540997 38685901 1146714 
10
825899021 804029588 800247222 192071445 468272519 580652734 836367373 84665276 291773017 397398501 
10
548890265 52458043 293866504 735835729 839010588 70426065 850356141 593377642 551847244 726657238 
10
15176200 154214246 152378290 74510767 87556515 113512989 36991523 5197719 46230156 143498675 
10
403095915 97600219 315553854 353282295 229399824 302922910 305011653 338562608 19890203 277665744 
10
381183556 523811290 231863918 635582568 54429420 548083818 642358830 230664723 4416596 579299771 
10
54293568 269138507 261898215 142883566 31287158 18704079 157001891 187256876 215081483 149593087 
10
14671550 48328214 70277652 78577560 4592258 12881787 11671170 78429474 44294424 36266399 
10
203921010 370839616 131119219 434691619 185028039 294423593 388777700 488600439 234185822 386907248 
10
109406531 475834857 542639941 284595739 584113764 484236386 331542995 461985683 617754952 270990702 
10
231397610 500422018 86877375 474104600 727617773 576917265 661535941 723384631 78753946 657302799 
10
52262213 33644536 47818539 5683552 54242024 42178081 19589848 22720268 36480514 15859757 
10
35305689 2979150 14353757 5183047 25329404 46931126 64120629 59112814 16447339 72838683 
10
207663976 597700995 200157425 543299583 180760515 477908205 15626469 212000193 127039286 481317983 
10
266051351 696426568 103486445 611441796 565516959 248288799 202363962 4632242 117379190 547754407 
10
78254159 268798509 34952843 214230465 266928778 268245543 287313002 104717988 279501439 96906425 
10
329655357 2038687 229629179 17132385 63227695 194864450 52758641 27611816 64879068 232090298 
10
338633879 52648900 595889311 607913029 690430079 147351025 101888732 219583318 493714394 329703693 
10
239477362 600198043 429964084 63371628 215196295 758133250 785759877 554922873 394223921 867446492 
10
500213652 618543688 268158398 45404191 25836261 190587713 480472506 354337096 91255371 522223639 
10
325353110 27014328 358474580 317826417 398663352 238202994 265019736 57320753 137270985 201972249 
10
187876327 184940460 86115910 277603876 265960101 208572499 143982246 62773456 242701330 89838921 
10
164047421 98102403 616500031 186787276 427738853 307168634 675538728 187047752 587374807 152727604 
10
915247117 279414468 619236508 220505288 525563796 98685328 280370115 647559070 149164587 913143097 
10
245052579 294266656 164813770 177928550 418474400 348535460 379819747 113254697 48475664 100245097 
10
415413806 267735840 434514338 486161048 432991230 382512681 253164530 479037421 252673879 3825690 

*/

